### ISSUE TITLE
Helpful error messages when the request fails

### ISSUE THREAD

**Issue by haseebnaseem** [niftylettuce/frisbee#51]
Is there a way that some helpful error messages can be thrown rather than just 'Network request failed' because that does not really tell anything about the failure. Any help will be appreciated.

**Comment by niftylettuce** [comment]
@haseebnaseem can you provide an example to reproduce the error you have?

did you see the docs and how you can catch `res.err`?  if there's a network error there's not much else we can do.  please provide a reproducible test case or more information please.

**Comment by niftylettuce** [comment]
you can also use Chrome Developer Tools and view the Network tab, then make a request and it should show their for you to inspect headers/request/response.

**Comment by haseebnaseem** [comment]
I am using the package for react native and it would be helpful in the way
that I can decide what error message to show to the user. For instance if
the api is down, or the connection user has is slow and timing out.

**Comment by OmgImAlexis** [comment]
@haseebnaseem not all of that can be accessed via the APIs frisbee uses. The same goes for other libs like this. The browser doesn't expose enough information in order for Frisbee to know what the reason was for the network not being there.

It could be a proxy setting that's blocking it, your wifi could have dropped, your internet could be slow, it could be the other end's connection, it could be your ISP is having issues with the site, it could be the edge server like Cloudflare is having issues, most of those all return the same error to us.

**Comment by haseebnaseem** [comment]
I understand that. Is there a way to handle network errors ? I am trying to use an interceptor by intentionally shutting down the api and the interceptors catches the error in the `responseError` function but even the api is back up again, the `responseError` function triggers.

**Comment by niftylettuce** [comment]
yeah wrap with a `try/catch`?
