### ISSUE TITLE
Bump es7 preset

### ISSUE THREAD

**Issue by OmgImAlexis** [niftylettuce/frisbee#60]
Waiting on https://github.com/meetearnest/eslint-config-earnest-es7/pull/30

**Comment by niftylettuce** [comment]
See v2.0.0 via `npm install frisbee@latest` or `yarn add frisbee@latest`.

This release includes refactoring for Node v10+ support, new tests with `ava` (instead of `mocha`), and use of `@babel/preset-env` targeted to Node v6.4+ and the last 2 versions of browsers (see `.babelrc` and `.browserslistrc`).
