### ISSUE TITLE
Releases notes for 2.0.0

### ISSUE THREAD

**Issue by theomathieubhvr** [niftylettuce/frisbee#64]
It would be nice if all of us know what changed in this package.

Thanks !

**Comment by niftylettuce** [comment]
Thanks for opening this.  There were no breaking changes, but I did completely change the test frameworks and added support for older versions of Node and the browser.

Updates in 2.0.0+:

- Rewrote tests to use `ava` (instead of `mocha`)
- Added `@babel/preset-env` with targets for `node` v6.4+ and the last 2 versions of browsers (see `.babelrc` and `.browserslistrc`)
- Updated Contributors list and section in `package.json`


Ref: https://github.com/niftylettuce/frisbee/commit/51b6a99ad1d432ad6d6c5a2bb5ad95a30ef3d886
